plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.20' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

allprojects {
    group = mod_group_id
    version = "${mod_version}.${mod_build}-${mod_prerelease}"

    repositories {
        mavenCentral()
        maven {
            name = 'Illusive Soulworks'
            url = uri('https://maven.theillusivec4.top/')
        }
        maven {
            name = 'RedlanceMinecraft'
            url = uri('https://repo.redlance.org/public')
        }
        maven {
            name = 'Nucleoid'
            url = uri('https://maven.nucleoid.xyz/releases')
        }
    }
}
