plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            logLevel = org.slf4j.event.Level.DEBUG
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            devLogin = true
            gameDirectory = file('runs/client')
        }
        client2 {
            client()
            gameDirectory = file('runs/client2')
        }
        server {
            server()
            gameDirectory = file('runs/server')
            programArgument '--nogui'
        }
        gameTestServer {
            type = 'gameTestServer'
            gameDirectory = file('runs/gameTestServer')
        }
        data {
            clientData()
            gameDirectory = file('runs/data')
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '**/*.bbmodel'
    exclude 'src/generated/**/.cache'
}

dependencies {
    implementation files(rootProject.file('libs/PlayerAnimationLibCore-1.2.3+mc.26.1.jar'))
    implementation files(rootProject.file('libs/PlayerAnimationLibNeo-1.2.3+mc.26.1.jar'))
    implementation files(rootProject.file('libs/mochafloats-5.0.0.jar'))

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
